### ISSUE TITLE
For loop has too many limitations. Need to improve that

### ISSUE THREAD

**Issue by Muntasib-creator** [AutomationSolutionz/Zeuz_Python_Node#41]
## Context

1. action range with colon should be enabled
2.  nD list should be handled without saying nested/ double nested
3. exit loop condition

**Comment by riz-hossain** [comment]
### ZeuZ Automated Issue Link Comment :fire: :fire:

| Test Case | Step Name | Status | Fail Reason | Milestone | Version |
|-----------|----------|--------|-------------|-----------|---------|
| [TEST-11151: zeuz web level1 actions Save and Compare Variable ](https://qa.zeuz.ai/Home/ManageTestCases/Edit/TEST-11151/) | Get & Save Text | Failed | Difference found in Left: {values_changed: {root: {new_value: 1, old_value: 2}}}  Difference foun... | a.s/d | a.sd |
